import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from '@playwright/test';
const url='https://timcgha.github.io/Webmaster/',out='evidence/wm-005/root-release',profile=path.resolve('.wm005-root-normal-profile');
fs.mkdirSync(out,{recursive:true});assert.equal(fs.existsSync(profile),false,'Fresh bounded verification profile required');
const opts={headless:true,channel:'chromium',viewport:{width:1280,height:720}},errors=[];let context,page;
async function open(){context=await chromium.launchPersistentContext(profile,opts);page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));await page.goto(url);await page.locator('#loading.hidden').waitFor({state:'attached',timeout:45000});assert.equal(await page.evaluate(()=>typeof window.__WM_DEBUG__),'undefined');assert.equal(await page.locator('#wm-preview').count(),0);}
try{
 await open();await page.getByRole('button',{name:/New Game/}).click();await page.getByRole('button',{name:/Slot 1/}).click();await page.getByRole('button',{name:/Normal/}).click();
 await page.locator('#hud-layer:not(.hidden) .objective-card').waitFor();await page.keyboard.down('w');await page.waitForTimeout(400);await page.keyboard.up('w');await page.waitForTimeout(700);
 await page.keyboard.press('Escape');const save=page.getByRole('button',{name:/Save Game/});await save.waitFor();assert.equal(await save.isEnabled(),true);await save.click();await page.locator('#toast-layer').filter({hasText:'Save confirmed'}).waitFor();await page.getByRole('button',{name:/Save & Quit/}).click();await page.getByRole('heading',{name:'WEBMASTER',exact:true}).waitFor();
 const saved=await page.evaluate(()=>Object.fromEntries(Object.entries(localStorage)));assert.ok(Object.keys(saved).length>0);assert.ok(Object.keys(saved).every(k=>!k.startsWith('webmaster.wm005-preview.v1:')));
 await context.close();context=null;await open();assert.deepEqual(await page.evaluate(()=>Object.fromEntries(Object.entries(localStorage))),saved);assert.equal(await page.getByRole('button',{name:/Continue/}).isEnabled(),true);await page.getByRole('button',{name:/Continue/}).click();await page.locator('#hud-layer:not(.hidden) .objective-card').waitFor();await page.waitForTimeout(1200);assert.deepEqual(errors,[]);
 await page.screenshot({path:out+'/ordinary-root-reopened.png'});fs.writeFileSync(out+'/ordinary-root.json',JSON.stringify({status:'PASS',url,method:'Ordinary root without debug/fixtures; real keyboard movement and menu Save Game/Save & Quit; browser process close/reopen Continue; identical saved generations.',errors},null,2));
}catch(error){fs.writeFileSync(out+'/ordinary-root-failure.json',JSON.stringify({status:'NOT_PASS',error:String(error),errors},null,2));throw error;}finally{await context?.close();}
